# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rediline"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Damien MATHIEU"]
  s.date = "2012-01-06"
  s.description = "Timeline library"
  s.email = "42@dmathieu.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/rediline.rb",
    "lib/rediline/entry.rb",
    "lib/rediline/object.rb",
    "lib/rediline/redis.rb",
    "lib/rediline/timeline.rb",
    "lib/rediline/timeline/user.rb",
    "lib/rediline/user.rb",
    "rediline.gemspec",
    "spec/entry_spec.rb",
    "spec/object_spec.rb",
    "spec/redis_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/timeline.rb",
    "spec/support/timeline_owner.rb",
    "spec/support/user.rb",
    "spec/timeline/user_spec.rb",
    "spec/timeline_spec.rb",
    "spec/user_spec.rb"
  ]
  s.homepage = "http://github.com/dmathieu/rediline"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Redis Backed Timeline"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, ["= 2.0.7"])
      s.add_runtime_dependency(%q<redis-namespace>, ["= 0.10.0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2"])
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, [">= 2"])
      s.add_runtime_dependency(%q<redis-namespace>, [">= 0.10"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2"])
    else
      s.add_dependency(%q<redis>, ["= 2.0.7"])
      s.add_dependency(%q<redis-namespace>, ["= 0.10.0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2"])
      s.add_dependency(%q<activemodel>, ["~> 3.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 2"])
      s.add_dependency(%q<redis-namespace>, [">= 0.10"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2"])
    end
  else
    s.add_dependency(%q<redis>, ["= 2.0.7"])
    s.add_dependency(%q<redis-namespace>, ["= 0.10.0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2"])
    s.add_dependency(%q<activemodel>, ["~> 3.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 2"])
    s.add_dependency(%q<redis-namespace>, [">= 0.10"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2"])
  end
end

